export default [
  {
    // Main source files
    files: ["**/*.js"],
    ignores: [
      "node_modules/**",
      "tests/**",
      // ESM module files — parsed separately (used by tests via import)
      "libs/background-core.js",
      "libs/classifier.js",
      "libs/recommendations.js",
      "libs/grading.js",
      "libs/message-router.js",
      "libs/migrations.js",
      // Config files
      "vitest.config.js",
      "eslint.config.mjs",
    ],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        // Browser globals
        chrome: "readonly",
        importScripts: "readonly",
        globalThis: "readonly",
        document: "readonly",
        window: "readonly",
        navigator: "readonly",
        console: "readonly",
        fetch: "readonly",
        URL: "readonly",
        performance: "readonly",
        requestAnimationFrame: "readonly",
        MutationObserver: "readonly",
        Blob: "readonly",
        location: "readonly",
        getComputedStyle: "readonly",
        matchMedia: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        confirm: "readonly",
        module: "readonly",
        // Extension shared globals
        CO2: "readonly",
        BENCHMARKS: "readonly",
        REGION_INTENSITY: "readonly",
        classifyResource: "readonly",
        isThirdParty: "readonly",
        BADGE_COLORS: "readonly",
        GRADE_THRESHOLDS: "readonly",
        OPTIMIZATION_FACTORS: "readonly",
        generateRecommendations: "readonly",
        getGrade: "readonly",
        // Side panel cross-file globals
        $: "readonly",
        el: "readonly",
        clearChildren: "readonly",
        currentData: "writable",
        previousResult: "writable",
        showState: "readonly",
        trapFocus: "readonly",
        getCSSVar: "readonly",
        render: "readonly",
        renderScore: "readonly",
        renderSparkline: "readonly",
        renderResourceBars: "readonly",
        renderHosting: "readonly",
        renderBenchmark: "readonly",
        renderQuickRecs: "readonly",
        renderTrend: "readonly",
        drawTrendChart: "readonly",
        renderTreemap: "readonly",
        renderThirdParty: "readonly",
        renderVisitComparison: "readonly",
        renderFixes: "readonly",
        checkForImprovement: "readonly",
        showToast: "readonly",
        checkRegression: "readonly",
        requestCurrentData: "readonly",
      },
    },
    rules: {
      // AC-P6-004: no unused vars (allow cross-file globals and catch params)
      "no-unused-vars": ["error", {
        args: "none",
        caughtErrors: "none",
        varsIgnorePattern: "^(TOTAL_ENERGY_PER_GB|cachedDPR|el|clearChildren|getCSSVar|showState|trapFocus|previousResult|currentData|render|renderScore|renderSparkline|renderResourceBars|renderHosting|renderBenchmark|renderQuickRecs|renderTrend|drawTrendChart|renderTreemap|renderThirdParty|renderVisitComparison|renderFixes|checkForImprovement|showToast|checkRegression|requestCurrentData)$",
      }],
      // AC-P6-004: no empty catch blocks
      "no-empty": ["error", { allowEmptyCatch: false }],
      // AC-P6-004: no undefined variables
      "no-undef": "error",
    },
  },
];
